### ISSUE TITLE
Feature Request: Expose outdoor_temperature as sensor

### ISSUE THREAD

**Issue by ccalica** [MizterB/homeassistant-infinitude#10]
Pretty easy to work around with a template sensor but being builtin would be nice.

**Comment by bdf0506** [comment]
I'm not sure how valid of a feature request this is.  It is already exposed in the attributes of the climate module. How else would you want it exposed? 

You can do a template sensor like this. When we first started with this project, you needed a json sensor to extract this data, it has since been placed in extra attributes. (See #4)

```  thermostat_outdoor_temp:
     value_template: '{{ states.climate.thermostat.attributes.outdoor_temperature }}'
     friendly_name: 'Thermostat Outdoor Temperature'
     device_class: temperature
     unit_of_measurement: '°F'

**Comment by MizterB** [comment]
This is possible, but would be a significant refactor.  Ideally I should treat Infinitude as a platform, and then expose climate and sensor devices on top of the platform.  I would need to separate out the current logic accordingly.  I have not built a component like that before, but should probably learn how.

For the moment, this is low priority for me since the attributes are exposed for template sensors.  I'll entertain a PR for the refactor if anyone wants to give it a try ;)

**Comment by ccalica** [comment]
Not worth it with creating a template so easy.
