### ISSUE TITLE
Ability to set Activity (Home/Away/Wake/Sleep)

### ISSUE THREAD

**Issue by bdf0506** [MizterB/homeassistant-infinitude#12]
Based on https://community.home-assistant.io/t/carrier-infinity-integration/17161/118

We should see how we can get this component to set the current activity for the thermostat. In the climate component, home assistant has the constant of SUPPORT_AWAY_MODE, however this is a boolean field and not a string field. I think we should be able to override this constant and allow the away mode to be a string field and not boolean.

First need to update the activity index, since it is erroneously listing away twice and missing wake.

```
ACTIVITY_INDEX = {
    "home": 0,
    "away": 1,
    "sleep": 2,
    "away": 3,
    "manual": 4
}
````
API calls to infinitude will probably look like this:

````
http://infinitude:8080/api/config/zones/zone/0/?hold=on&holdActivity=home&otmr=
http://infinitude:8080/api/config/zones/zone/0/?hold=on&holdActivity=away&otmr=
http://infinitude:8080/api/config/zones/zone/0/?hold=on&holdActivity=sleep&otmr=
http://infinitude:8080/api/config/zones/zone/0/?hold=on&holdActivity=wake&otmr=
````
But, if we set the hold on all the time without an end time (in the otmr field), the normal Infinity schedule won't ever really take affect, unless you do scheduling with HA instead of the Infinity itself. If we want to respect the current schedule (which is probably the correct way to do this), would need to be able to first do a query to find out when the next scheduled activity is, and instead only do a hold until the next scheduled activity, that way the schedule on the Infinity would still apply. We already know this information in self._nextActivityStart and self._nextActivity. Just have to think through the best way to write this into the component.

**Comment by MizterB** [comment]
_Copying my response for the HA forums, which is more appropriately left here_

Thanks. ACTIVITY_INDEX actually is used is in the set_temperature and set_fan_mode calls, because the Infinitude API (and the XML schema) references activities by ID, not name. But you are right, I’m only using the manual activity right now.

The logic being used right now is that when HA manually overrides either of those settings, the thermostat will apply the new temp ofrfan setting to the zone’s ‘manual’ activity. To then activate those settings, the manual activity is then enabled and ‘hold until’ flag is set, which effectively applies those settings until the next scheduled activity change (same default behavior as the thermostat).

As I’m writing this, I am remembering that this same approach is exactly what I need to do for your request - just apply a “hold until” on the requested activity, which will switch to that activity until the next schedule change!

To clarify the use of Away mode, if HA enables this setting, I place an indefinite hold on the ‘away’ activity profile. It’s probably not ideal if someone uses it for something like a ‘vacation mode’, where they might want the target temp to be something different than their daily ‘away’ profile. This is why I wanted to expose the ability to change the Hold setting through a service, so a script/automation/etc could enable such a scenario.

To conclude, services are the right way to provide the functionality both you and I are looking for (extending beyond the core capabilities of the HA climate platform). I just need to define the service handlers and create the corresponding services.yaml file - the rest of the foundation is already there.

**Comment by MizterB** [comment]
Take a look at the latest release, which includes an `infinitude.set_hold_mode` service.

In its simplest form you can just pass `{"activity": "away"}` to it, which would override the current activity on all zones to 'away' and hold until the next schedule change.  You can pass additional data to replicate the other override options available on the thermostat.

Additional details are in the service documentation.

**Comment by bdf0506** [comment]
Great work here! Is there any way to add this into the GUI on the Lovelace card? Would be nice to be able to select the activity in a dropdown on the card directly, instead of having to always have to mess with a service.

Otherwise, looks like you can set this with automation with the service that you built on top of this.
