### ISSUE TITLE
Manual override settings always revert?

### ISSUE THREAD

**Issue by adamurban** [MizterB/homeassistant-infinitude#41]
If I manually adjust the temperature via home assistant or on the thermostat itself, it always reverts to whatever the “scheduled” preset was after a few seconds.

This has been working fine for some months, so not sure what broke. I tried restarting everything to no avail; not seeing any logs or errors either. User error? Or did something break?

**Comment by adamurban** [comment]
…if I change the set point on a preset, that works.. but if I set a manual override, Eg by adjusting temp setpoint in HA, it always just jumps back to the preset after a few seconds.

**Comment by brettonw** [comment]
I believe that you are seeing this behavior because your heat set point is higher than the cooling set point you are trying to set.

-set the thermostat to heat mode
-set the temperature to 55 (or something lower than you will ever set your cooling point)
-set the thermostat back to cool mode
- set the temperature you would like to cool to

In the winter you have to reverse this.

I set up an elaborate automation in HA to handle this for me, after a lot of trial and error during seasonal changeovers. It’s an infinity thermostat behavior, not an infinitude or home assistant behavior.

**Comment by adamurban** [comment]
No, that’s not it.. heat set point is at 67, and the system is set to cool. Maybe it’s a timezone bug? I noticed when I just set a manual override in HA, it sets the “hold until” checkbox in infinitude.. but the time is in the past?

![0F8C7479-43AD-4B26-9E67-5F8748400512](https://user-images.githubusercontent.com/3276234/173714388-54bcf785-3a90-4ad4-ac7c-7bdbd1c51790.png)

**Comment by adamurban** [comment]
If it is indeed a time stamp formatting thing, this logic looks like it could be the culprit:

https://github.com/MizterB/homeassistant-infinitude/blob/6f111c7f099deb1f26f59533e70166598e0a07d8/custom_components/infinitude/climate.py#L769

Which gets the time stamp of the “next event” and sets the hold until that time.

**Comment by brettonw** [comment]
Can you share the “status” screen?

**Comment by adamurban** [comment]
I think the issue is actually that the next event is tomorrow morning, so the "hold until" is 8:00a, has already passed, so gets reverted? So maybe we need some logic to hold until midnight if the next event is the next day?

![image](https://user-images.githubusercontent.com/3276234/173722865-a5159714-18a1-422b-b4ad-7ef2faa077e4.png)

**Comment by adamurban** [comment]
> Can you share the “status” screen?

(Some of the) Status page:
![image](https://user-images.githubusercontent.com/3276234/173723059-94213280-abcd-4e40-97ec-789d98890427.png)

Let me know if you want any other details...

**Comment by brettonw** [comment]
You say you are trying to manually set the temperature and it resets, what are you trying to set it to?

**Comment by adamurban** [comment]
I originally had my "Sleep" profile set to 73 and was trying to set the temperature to 70 manually via home assistant.

The only way I can get it to stick is to update the profile though, so you can see I updated "Sleep" to 70 when the screenshots above were taken. At that point, for testing, I was trying to set it to 69.

**Comment by adamurban** [comment]
Also, my theory RE "timestamp" didn't seem to pan out...
I edited my climate.py to have this logic:
```
        if until is None:
            if self.activity_next_start.hour < datetime.datetime.now().hour:
                until = "23:59"
            else:
                until = self.activity_next_start.strftime("%H:%M")
```

And indeed, when I manually adjust the temperature in HA, I see it change in infinitude with a hold set to 23:59.... however, after a few seconds, it reverts to the scheduled profile with an 8:00a hold again:
<img width="374" alt="Screen Shot 2022-06-14 at 11 41 37 PM" src="https://user-images.githubusercontent.com/3276234/173732920-f2d0aa44-1818-4fb8-9262-704bb859b19d.png">
<img width="345" alt="Screen Shot 2022-06-14 at 11 41 43 PM" src="https://user-images.githubusercontent.com/3276234/173732937-d65b1b72-8c11-42f6-bd73-6fc7ef9a521a.png">

**Comment by brettonw** [comment]
I'm not sure what could be causing this, then. I had to deal with something like this when I first set up Infinitude, and it was by accident that I noticed it was rejecting attempts to set the cool point below the heat set point - but the only reason the heat set point was high was because I had switched it from heat to cool while the heat was on. When I manually set the heat set point very low, the cooling set points would stick. In general, I think the thermostat rejects any attempt to set something that it sees as invalid for some reason, so look to see if there's some other combination of factors that is invalid that could be causing it.

**Comment by brettonw** [comment]
I believe that you are seeing this behavior because your heat set point is higher than the cooling set point you are trying to set.

-set the thermostat to heat mode
-set the temperature to 55 (or something lower than you will ever set your cooling point)

In the winter you have to reverse this.

**Comment by MizterB** [comment]
Should be addressed in https://github.com/MizterB/homeassistant-infinitude-beyond
