### ISSUE TITLE
Zones:  'NoneType' object is not scriptable

### ISSUE THREAD

**Issue by thetrebor** [MizterB/homeassistant-infinitude#44]
I can't tell if this is a quirk with my installation or if this is a problem with the plugin.  It appears to be crashing on zone names.  I've tried various iterations of naming them in the configuration.yaml or excluding the key.  I've updated the zone names in the thermostat too and made them match or not match.

Not sure if this is just a symptom of the upstream problem with infinitude either.  I suspect the device should show up but as unreachable if the infinitude proxy is not working right.

Just can't seem to get it to work:

Logger: homeassistant.components.climate
Source: custom_components/infinitude/climate.py:111 
Integration: Climate ([documentation](https://www.home-assistant.io/integrations/climate), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+climate%22)) 
First occurred: 12:10:56 PM (1 occurrences) 
Last logged: 12:10:56 PM

Error while setting up infinitude platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/infinitude/climate.py", line 111, in setup_platform
    zones = status["zones"][0]["zone"]
TypeError: 'NoneType' object is not subscriptable

**Comment by thetrebor** [comment]
I reinstalled Home Assistant and made sure the zones were set up properly and the issue is still occurring.
Not sure what else to check.

**Comment by dookie-x** [comment]
Ditto over here. Any progress on solving this?

**Comment by Elder-HVAC-Man** [comment]
Anyone have a solution for this?  Just installed and am having the same issue.

Error while setting up infinitude platform for climate

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 353, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/infinitude/climate.py", line 111, in setup_platform
    zones = status["zones"][0]["zone"]
            ~~~~~~^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable

**Comment by MeCJay12** [comment]
For all you struggling with this, I had this issue this morning and I was able to fix it. It looks like this is just a case of missing error handling in the integration. The integration assumes there is at least one zone because your thermostat always has at least one default zone but if you have having issues upstream, the Infinitude proxy returns 'null' then there are no zones, then you get this error. You can check if you are having upstream issues by going to your browser and navigating to 'http://<ip-of-infinitude>:<port>/api/status'. If the page says null you need to look upstream. It should have a bunch of lines of json (?) text. Another test is if you go to ''http://<infinitude>:<port>/' it should be populated with info on your system. If it has minimal information, you have an upstream issue.

As for troubleshooting upstream, you can check the Docker logs on Infintude and it should have hundreds of lines of connection information. If you just see this then you have and issue:
```
docker logs Infinitude
MODE is set to Production
[2023-10-14 16:36:21.99255] [7] [info] Listening at "http://*:3000"
```

I dug around in the manual for Infinitude and apparently, it only works with versions up to 4.05 afterwhich Carrier switched to MQTT which Infinitude doesn't support. I happened to have 4.47 installed so I had to downgrade my thermostat and reboot then everything worked. If you need to downgrade like I did, Carrier's website has the latest firmware availible but hides older firmware. Just get the download link for the current firmware and change out the version in the URL to get the older firmware.

**Comment by MizterB** [comment]
Please retry in https://github.com/MizterB/homeassistant-infinitude-beyond
