### ISSUE TITLE
Infinitude Add-On?

### ISSUE THREAD

**Issue by GizmoGoody** [MizterB/homeassistant-infinitude#49]
This is not an issue against this integration. It seems to be working well for me. I would have posted this in the Discussions section, but it doesn't appear to be enabled.

Since HA supervised does not support  Portainer, requiring an unsupported installation of the unofficial Portainer add-on, would it be possible for you to create an Infinitude add-on like I've seen other developers do with projects like Z-Wave JS UI, etc?

Here's [my discussion](https://github.com/alexbelgium/hassio-addons/discussions/626) on the unofficial Portainer add-on repo for more context.

**Comment by WilliamAlexanderMorrison** [comment]
@GitHubGoody I had a similar idea a few days ago, and was able to get it to work by creating a local/custom add-on. To be pretty blunt, I'm a usually a "stand on the shoulders of giants" type of a guy when it comes to technology, but I was able to fumble my way to getting it to work. I took some notes in my repo and added the files that ended up working for me. https://github.com/WilliamAlexanderMorrison/infinitude-hablue-addon

**Comment by Elder-HVAC-Man** [comment]
@WilliamAlexanderMorrison So no proxy server required?

**Comment by WilliamAlexanderMorrison** [comment]
@Elder-HVAC-Man the proxy server is still required. 

Home Assistant (my particular hardware is a HA Blue) is running off of a series of containers. HA supports adding additional containers with their "Addon" feature. I was a little intimidated to try and create a new custom Addon, but since the work has been done on the Infinitude repo to make it container ready, it wasn't to painful to connect the dots.

The result is that the Infinitude proxy server is running on the same hardware as my HA, side by side in another container, that is exposed to my local network on port 3000. HA gives a nice UI for the container itself, its logs in case there are any issues, and buttons to turn it on or off.

I configured my thermostat to point at the IP:port on my internal network that represents my HA hardware. I can set up my router to prevent the thermostat from accessing the Internet at large because I'm security conscious (read: paranoid).

So now I have:
* a smart thermostat isolated from the Internet
* a single piece of hardware for the thermostat to send data and for running HA
* the proxy server Infinitude processing that data and making it available
* The HACS infinitude-integration getting the data from Infinitude and making it available to HA

Hope that helps explain my set up!

**Comment by Elder-HVAC-Man** [comment]
Thanks for the explanation.  If you don’t mind, what firmware version is your thermostat at?  I think I need to downgrade as the current versions aren’t compatible, or so it seems.
Larry


Sent from AT&T Yahoo Mail for iPad


On Friday, August 11, 2023, 7:15 AM, William Morrison ***@***.***> wrote:




@Elder-HVAC-Man the proxy server is still required.

Home Assistant (my particular hardware is a HA Blue) is running off of a series of containers. HA supports adding additional containers with their "Addon" feature. I was a little intimidated to try and create a new custom Addon, but since the work has been done on the Infinitude repo to make it container ready, it wasn't to painful to connect the dots.

The result is that the Infinitude proxy server is running on the same hardware as my HA, side by side in another container, that is exposed to my local network on port 3000. HA gives a nice UI for the container itself, its logs in case there are any issues, and buttons to turn it on or off.

I configured my thermostat to point at the IP:port on my internal network that represents my HA hardware. I can set up my router to prevent the thermostat from accessing the Internet at large because I'm security conscious (read: paranoid).

So now I have:
   
   - a smart thermostat isolated from the Internet
   - a single piece of hardware for the thermostat to send data and for running HA
   - the proxy server Infinitude processing that data and making it available
   - The HACS infinitude-integration getting the data from Infinitude and making it available to HA

Hope that helps explain my set up!

**Comment by WilliamAlexanderMorrison** [comment]
From the service->model/serial numbers page:
Software version: 131493-14.02
Wi-fi firmware version: 2.5.5,1.6.8

**Comment by MizterB** [comment]
Out of scope for this integration
