### ISSUE TITLE
Hold Until Time Format

### ISSUE THREAD

**Issue by GizmoGoody** [MizterB/homeassistant-infinitude#59]
Can the **hold_until** attribute be changed to match the full timecode format used by scheduled_activity_start and next_activity_start? I'm trying to use it in some templates, but cannot manipulate it using the typical methods (e.g. as_timestamp and [these format codes](https://strftime.org/)) since it's just the time as a string.

![image](https://github.com/MizterB/homeassistant-infinitude/assets/46235745/d6b4fdcd-a2d7-4559-9bfc-5934c30c7683)

**Comment by nebulous** [comment]
The thermostat itself only supports quarter hour holds - it actually stores the hold as a single byte which can be thought of as "quarter hours since midnight". So Infinitude needs to maintain this attribute in the current suboptimal string representation. I think you should be able to use `strptime` to parse that in a HA template, though. A quick sanity check on my system seemed to work at least `strptime(state_attr('climate.primary', 'hold_until'), "%H:%M")`

**Comment by GizmoGoody** [comment]
Interesting. Thanks, I'll take another hack at it.

To be sure, I assume a hold also cannot exceed 24 hours from the start of the hold? Otherwise, it seems a date would be necessary.

**Comment by MizterB** [comment]
Please upgrade to https://github.com/MizterB/homeassistant-infinitude-beyond.  All timestamps are in ISO format.
